name: "JFrog-GitHub OIDC Integration"
on: push

permissions:
  id-token: write
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Print
         run: env | sort
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.13'
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: 'vn-github'
           version: latest
           disable-job-summary: false
       - name: Ping Artifactory
         run: jf rt ping
       - name: python config
         run: jf pip-config --repo-resolve=vn-gh-pipy-test --repo-deploy=vn-gh-pipy-local
       - name: Install setuptools and wheel
         run: jf pip install --upgrade setuptools wheel
       - name: build
         run: jf pip install -r requirements.txt
       - name: Build Python package
         run: python setup.py sdist bdist_wheel
       - name: Publish Python package to Artifactory
         run: jf rt upload "dist/*.tar.gz" vn-gh-pipy-local/ --build-name=my-python-app --build-number=${{ github.run_number }}
       - name: Publish Build Info
         run: jf rt build-publish my-python-app ${{ github.run_number }}
